version: 0.2

phases:

  install:
    runtime-versions:
      golang: 1.16

    commands:

    # Use go modules rather than GOPATH
    - export GO111MODULE="on"

    # Install Testify to use common assertions and mocks in tests
    - go get -u github.com/stretchr/testify

  build:
    commands:

    # Fetch all dependencies
    - go get ./...

    # Check for common Go application problems with 'go vet'
    - go vet ./...

    # Run all tests included with our application
    - go test ./...

    # Create executable for lambda
    - go build -o ./interacter/main ./interacter/...

artifacts:
  files:
  - interacter/*
